function nodes = importnodes(filename)
%Identify the import options for nodes.
varNames_nodes = {'ID', 'x', 'y', 'hctg'};
varTypes_nodes = {'double', 'double', 'double', 'double'};
opts_nodes = delimitedTextImportOptions('VariableNames',varNames_nodes,...
                                  'VariableTypes',varTypes_nodes,...
                                  'Delimiter', ',',...
                                  'ExtraColumnsRule', 'ignore',...
                                  'DataLines', [1,inf],...
                                  'EmptyLineRule', 'read',...
                                  'NumVariables', 4);
nodes = readtable(filename, opts_nodes);
end